### ISSUE TITLE
'AuthenticationServices/AuthenticationServices.h' file not found. in ios using swift 

### ISSUE THREAD

**Issue by Paragdhanani** [AzureAD/microsoft-authentication-library-for-objc#714] opened 2019-10-10 12:11 UTC

**Comment by Paragdhanani** [comment] 2019-10-10 12:13
When i run the project it gives me Build Faild... and Error is AuthenticationServices/AuthenticationServices.h' file not found.
Please give me the solution

**Comment by oldalton** [comment] 2019-10-11 00:33
@Paragdhanani, how are you consuming MSAL? CocoaPods/Carthage/direct download? Can you please provide a bit more info on your setup?

**Comment by oldalton** [comment] 2019-10-18 03:05
@Paragdhanani, can you provide the info requested above? Thanks!

**Comment by oldalton** [comment] 2019-10-31 22:13
@Paragdhanani, I'll be closing this issue because we haven't been able to reproduce it. Please reopen the issue with any additional information you can provide if you're still seeing it. Thanks!

**Closed by oldalton** 2019-10-31 22:13 UTC
Labels: needs-information
