### ISSUE TITLE
macOS: Acquiring a token stopped working on the Big Sure beta 9 (20A5384c)

### ISSUE THREAD

**Issue by eRDe33** [AzureAD/microsoft-authentication-library-for-objc#1123] opened 2020-10-01 13:52 UTC
Hi,
I've tried the MSAL library on the latest macOS Big Sur Beta (version 11.0 Beta (20A5384c)) and it seems that acquiring a token has completely stopped working on this system version.

Every time you call `acquireToken(with:, completionBlock:)`, acquiring token ends with a cancellation error (_Could not acquire token: Error Domain=MSALErrorDomain Code=-50005 "(null)" UserInfo={MSALErrorDescriptionKey=User cancelled the authorization session.}_). This cancellation error is thrown immediately after you click the "Continue" button in the attached alert.
![Screenshot 2020-10-01 at 15 20 02](https://user-images.githubusercontent.com/12135948/94817737-9d8ffa80-03fd-11eb-80f2-e3639762b8cd.png)

I've successfully replicated this problem in your sample app, so if it helps, here is a MSAL log dump:
```
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] Querying MSAL accounts with parameters (identifier=Masked(null), tenantProfileId=Masked(null), username=Masked(null), return only signed in accounts 1)
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] Keychain find status: -25300
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] (Default accessor) Get accounts.
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] Keychain find status: -25300
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] Keychain find status: -25300
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] (Default accessor) Looking for token with aliases (null), tenant (null), clientId 2a858956-70de-42b9-b5db-d566eb1fb820, scopes (null)
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] Keychain find status: -25300
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] (Default accessor) No accounts found in default accessor.
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] (Default accessor) No accounts found in other accessors.
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] Found MSAL accounts with count 0
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27] Found MSAL account with current account Masked(null), previous account Masked(null)
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27 - F75D187C-A28E-4FDE-8B65-498AD94A13D1] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
    "user.read"
)
                                     extraScopesToConsent:(null)
                                                  account:Masked(null)
                                                loginHint:Masked(null)
                                               promptType:MSALPromptTypeSelectAccount
                                     extraQueryParameters:(null)
                                                authority:(null)
                                              webviewType:MSALWebviewTypeDefault
                                            customWebview:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27 - F75D187C-A28E-4FDE-8B65-498AD94A13D1] [MSAL] Beginning interactive flow.
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27 - F75D187C-A28E-4FDE-8B65-498AD94A13D1] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
TID=161142 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:27 - F75D187C-A28E-4FDE-8B65-498AD94A13D1] [MSAL] Resolved authority, validated: YES, error: 0
TID=161699 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:29] Creating Error with description: User cancelled the authorization session.
TID=161699 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:29 - F75D187C-A28E-4FDE-8B65-498AD94A13D1] [MSAL] Interactive flow finished. Result (null), error: -51700 error domain: MSIDErrorDomain
TID=161699 MSAL 1.1.3 Mac 10.16.0 [2020-10-01 13:24:29 - F75D187C-A28E-4FDE-8B65-498AD94A13D1] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50005) Masked(not-null)
```

It seem's that ASWebAuthenticationSession have stopped working properly on the latest Big Sur for some reason.

Have you come across this problem already? It could be quite a problem when the Big Sur will be released.

Thanks.

**Comment by eRDe33** [comment] 2020-10-02 11:32
**Available workaround:**
When you set _prefersEphemeralWebBrowserSession_ to true on used _MSALWebViewParameters_, everything will start again. Of course, you will lose the benefits of a non-ephemeral authentication session (more info here: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc).

``` Swift
webviewParameters.prefersEphemeralWebBrowserSession = true
```

**Comment by kaisong1990** [comment] 2020-10-02 21:33
@eRDe33 Thanks for your post, we tried with a different beta version, and cannot reproduce this issue. We will try with the Big Sur version as you mentioned again. Meanwhile, could you try to run with MSAL 1.1.10 which is our latest version?

**Comment by eRDe33** [comment] 2020-10-05 07:59
@kaisong1990 I tried it with the latest version 1.1.10 and unfortunately the result was the same.
```
TID=130969 MSAL 1.1.10 Mac 10.16.0 [2020-10-05 07:46:54] Creating Error with description: User cancelled the authorization session.
TID=130969 MSAL 1.1.10 Mac 10.16.0 [2020-10-05 07:46:54 - 368A0331-08E8-4406-A07C-4E210A14FD55] [MSAL] Interactive flow finished. Result (null), error: -51700 error domain: MSIDErrorDomain
TID=130969 MSAL 1.1.10 Mac 10.16.0 [2020-10-05 07:46:54 - 368A0331-08E8-4406-A07C-4E210A14FD55] [MSAL] acquireToken returning with error: (MSALErrorDomain, -50005) Masked(not-null)
```
Meanwhile my colleague tried it on the previous version of the Big Sur Beta and there everything worked fine. After he updated to the latest Big Sur version the activation started failing, so I think the problem was introduced in the latest Big Sur realease (20A5384c).

**Comment by guidedways** [comment] 2020-10-06 03:42
> **Available workaround:**
> 
> When you set _prefersEphemeralWebBrowserSession_ to true on used _MSALWebViewParameters_, everything will start working again. Of course, you will lose the benefits of a non-ephemeral authentication session (more info here: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237231-prefersephemeralwebbrowsersessio?language=objc).
> 
> 
> 
> ``` Swift
> 
> webviewParameters.prefersEphemeralWebBrowserSession = true
> 
> ```

Thanks. That worked for me too. Same issue, all our Big Sur users having the same problem.

**Comment by mattvlas** [comment] 2020-10-06 03:45
While an OK workaround, this inhibits some really nice usability benefits of the shared auth cache to simplify SSO.

I can confirm this only impacts this specific beta build... With any luck it will just be fixed in the next update.

@kaisong1990 have you raised an issue with Apple?  I'm, happy to do so as well if you can provide any helpful details about why this has stopped working.

**Comment by kaisong1990** [comment] 2020-10-06 07:49
@eRDe33  Thanks for providing more details and workaround to unblock the development.

**We are able to reproduce this issue on Big Sur Beta 9 with both Xcode 12.0.1 and Xcode 12.2 beta 2**. Internally, we are starting a ASWebAuthenticationSession by providing a completion block and some other params to Apple SDK, and have no control over the popover behavior. 

@mattvlas We posted the issue in the Apple developer forums and created a radar internally to Apple devs, if not get a response/confirmation regarding this issue, will escalate this issue with Apple next week.

Meanwhile will keep this thread update-to-date if anything was found.

Thanks

**Comment by kaisong1990** [comment] 2020-10-06 22:46
An Apple engineer replied that when he tried with this [sample code](https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service?language=objc) provided by Apple, he can reproduce the same issue on beta 9. I have provided the feedback id, and he has request access to the bug report for further updates.

**Comment by eRDe33** [comment] 2020-10-16 10:32
@kaisong1990 just for info. In the latest version of Big Sur beta 10 (20A5395g), the system bug causing this issue is fixed and everything works fine. Thanks for your effort.

**Closed** 2020-10-16 22:23 UTC
Labels: question

**Comment by ShmuelCammebys** [comment] 2024-06-03 14:59
We are experiencing this issue for users on Sonoma 14.5 (23F79)
