### ISSUE TITLE
Issue with parent view controller in MSALWebviewParameters

### ISSUE THREAD

**Issue by odarynakorolevych** [AzureAD/microsoft-authentication-library-for-objc#796] opened 2019-12-06 15:03 UTC
Hello, I am using MSAL for SSO login with prefersEphemeralWebBrowserSession set to TRUE for iOS 13 (which uses under the hood ASWebAuthenticationSession as far as I know). 

I found an issue with my view controller, that I set as parentViewController in MSALWebviewParameters, and found that after authentication it doesn't seem to deallocate from memory. I investigated this issue and found that all objects from MSAL and SafariServices cannot deallocate too, because they are captured by different blocks (screenshot is attached). 

Am I doing something wrong or that is an issue by your or Apple side?

![Screen Shot 2019-12-06 at 5 01 30 PM](https://user-images.githubusercontent.com/58599882/70332382-1fe57780-184a-11ea-9978-d993fc079107.png)

**Comment by odarynakorolevych** [comment] 2019-12-10 09:27
Any news about this issue?

**Comment by oldalton** [comment] 2019-12-10 17:55
@antrix1989

**Comment by rohitnarula7176** [comment] 2019-12-19 00:23
@odarynakorolevych Thank you for reporting this issue. We recently pushed a test branch with a fix for this issue. Can you please try that out and confirm if your issue is resolved. Here is the link for the branch:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/pull/807

**Comment by odarynakorolevych** [comment] 2019-12-19 14:12
@rohitnarula7176 I checked on your branch, and found no memory leaks! Parent view controller successfully deallocated and no leaks in the library.

**Comment by rohitnarula7176** [comment] 2019-12-20 18:59
@odarynakorolevych Thank you for confirming that the issue is resolved for you. The branch with the fix is now merged in dev and will be part of our next release. Closing this issue for now.

**Closed by rohitnarula7176** 2019-12-20 18:59 UTC
Labels: question
