### ISSUE TITLE
Release Frameworks?

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1180] opened 2020-12-17 21:56 UTC
In the latest releases the .tar.gz and the .zip files are the same as the Sources.zip files, i.e. I don't see any "release" versions of the Frameworks. Can we have those to simply download and copy into our projects? Carthage has stopped working properly with Xcode 12 and I'm now seeing code signing errors when trying to use MSAL.

Would be great to have Swift PM supported eventually.

**Comment by oldalton** [comment] 2020-12-18 01:24
We don't currently release MSAL as a framework. You can build your version from the source code.

**Comment by oldalton** [comment] 2020-12-18 01:25
Closing as a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/737 for SwiftPM.

**Closed by oldalton** 2020-12-18 01:25 UTC
Labels: question
