### ISSUE TITLE
MSALErrorDomain error -50000 when calling getDeviceInformation

### ISSUE THREAD

**Issue by nick-mcdonald-dtnb** [AzureAD/microsoft-authentication-library-for-objc#2069] opened 2024-02-28 02:04 UTC
### Overview
I've developed a small macOS app to facilitate the company portal registration flow for Intune compliance on macOS devices, we're a 3rd party device compliance partner building our initial integration. 

The app launches the Company Portal in registration mode, waits for registration, then extracts the `extraDeviceInformation` object from `getDeviceInformation` to retrieve the Intune device ID for testing purposes.

### Problem
The app/msal functions correctly on physical macOS devices, with MSAL providing the `extraDeviceInformation` as expected. 

However, when run on macOS Virtual Machines (VMs) using platforms like Anka, Orca Toolkit, Parallels, etc., we consistently encounter an MSAL error: "The operation couldn't be completed. (MSALErrorDomain error -50000.)"

### Reproduction Steps
1. Launch an app on a macOS VM that calls `getDeviceInformation` via MSAL, after performing company portal registration.
2. Observe the error: "The operation couldn't be completed. (MSALErrorDomain error -50000.)"

### Observations
It seems that something outside of our control isn't functioning correctly on Virtual Machines for unknown reasons.

## Environment Details
- macOS Version: 14.3.1
- MSAL Version: 1.3.0
- Virtualization Platforms: Anka, Orca Toolkit, Parallels, etc. (all leverage macOS virtualization framework)

### Additional Details
I've enabled verbose logging in MSAL to gather more information. Below are the logs from a VM post-registration flow:

#### MSAL Logs from VM:
```
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Using "Masked(not-null)" Team ID.
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Init MSIDKeychainTokenCache with keychainGroup: Masked(not-null)
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Init MSIDMacACLPersistentTokenCache
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Init MSIDMacKeychainTokenCache with keychainGroup: Microsoft Credentials.
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Querying device info
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] [MSAL] GetDeviceInfo: Should call Sso Extension decision: 1
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] [MSAL] GetDeviceInfo: Creating Sso Extension request
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] [MSAL] GetDeviceInfo: Invoking Sso Extension with ssoExtensionRequest: Masked(not-null)
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Could not write broker key -34018
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Encountered error with code -51808, description Masked(not-null)
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] [MSAL] Failed to retrieve broker key with error MaskedError(MSIDErrorDomain, -51808)
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] Failed to create json for MSIDBrokerOperationGetDeviceInfoRequest class, brokerKey is nil.
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] Creating Error with description: Failed to serialize SSO request dictionary for get_device_info
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] [MSAL] GetDeviceInfo: Receiving results from Sso Extension with device info: Masked(null), error: MaskedError(MSIDErrorDomain, -51111)
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] GetDeviceInfo: Error getting device info: MaskedError(MSIDErrorDomain, -51111)
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] [MSAL] Checking Legacy keychain for registration.
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Failed to find workplace join private key with status -25300
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10 - A444AA3A-8D1F-4819-8F50-83990CA5E6B5] [MSAL] Checking keychain for default registration done using ECC key.
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] Error Domain=MSIDKeychainErrorDomain Code=-34018 "(null)" UserInfo={MSIDCorrelationIdKey=A444AA3A-8D1F-4819-8F50-83990CA5E6B5, MSIDErrorDescriptionKey=Could not get default primary registration tenantId.}
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] GetDeviceInfo: Completing filling device info: Masked(not-null), error: MaskedError(MSIDErrorDomain, -51111)
Failed to fetch device information: The operation couldn’t be completed. (MSALErrorDomain error -50000.)
MSAL log: TID=24515 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 01:33:10] getDeviceInformation returning with error: (MSALErrorDomain, -50000) Masked(not-null)
```

#### MSAL Logs from physical test device: (`extraDeviceInformation` returned as expected)
```
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22] Using "Masked(not-null)" Team ID.
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22] Init MSIDKeychainTokenCache with keychainGroup: Masked(not-null)
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22] Init MSIDMacACLPersistentTokenCache
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22] Init MSIDMacKeychainTokenCache with keychainGroup: Microsoft Credentials.
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22] Querying device info
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22 - 90B2717D-91F4-4E02-BCBD-6B1311896864] [MSAL] GetDeviceInfo: Should call Sso Extension decision: 0
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22 - 90B2717D-91F4-4E02-BCBD-6B1311896864] [MSAL] Broker is not present on this device. Defaulting to personal mode
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22 - 90B2717D-91F4-4E02-BCBD-6B1311896864] [MSAL] Checking Legacy keychain for registration.
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22] Retrieved WPJ issuer 0x1v0
	&ò,dnet0
	&ò,dwindows0UMS-ORGANIZATION-ACCESS0+U$82DBACA4-3E81-46CA-9C73-0950C1EACA97
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22 - 90B2717D-91F4-4E02-BCBD-6B1311896864] [MSAL] Returning RSA private device key from legacy registration.
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22] GetDeviceInfo: Completing filling device info: Masked(not-null), error: Masked(null)
Extra Device Information:
primary_registration_metadata_device_id: REDACTED
primary_registration_metadata_certificate_thumbprint: REDACTED
primary_registration_metadata_tenant_id: REDACTED
primary_registration_metadata_upn: REDACTED
primary_registration_metadata_cloud_host: login.microsoftonline.com
MSAL log: TID=3281694 MSAL 1.3.0 Mac 14.3.1 [2024-02-28 02:00:22 - 90B2717D-91F4-4E02-BCBD-6B1311896864] [MSAL] Retrieved device info Masked(not-null)
```

**Comment by Veena11** [comment] 2024-02-28 03:49
Hi @nick-mcdonald-dtnb , thanks for providing the logs. 
Couple of observations from the logs from failing VM :

- sso extension seems to be active on the device but the request via sso extension failed with broker key error. Are you using the Microsoft sso extension via Company portal ? 
- further the logs say MSAL could not find WPJ registration artifacts from keychain. 
- Do you happen to know if device registration attempt via Company Portal was successful? 

To further investigate, could you repro and share company portal logs via Help -> Send diagnostic report and share the incident ID ?

<img width="369" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-objc/assets/9446116/e896d5cf-7727-4668-820f-799b6daa2abf">

**Comment by nick-mcdonald-dtnb** [comment] 2024-02-28 16:43
@Veena11 Thank you for your quick response here :)

I've repro'd this and have a full screen recording [here](https://youtu.be/PJ7Ua891Qrk) of the end-to-end flow available for you.

I also submitted that diagnostic report as requested.

- The first one I sent immediately after successful WPJ but before clicking "done" and my app subsequently requesting (and receiving a failure response) from MSAL. This is the one you can see be submitted in the video. 
  ID: 798AEAC4

- The second one, I sent after re-opening company portal manually from /Applications post WPJ process, and after my app received the error from MSAL. 
  ID: 0A0911AD

**Comment by Veena11** [comment] 2024-02-28 22:08
Thank you @nick-mcdonald-dtnb for the repro and logs , could you also confirm whether your MSAL app has the access to the keychain group 
com.microsoft.identity.universalstorage in project capabilities ?

**Comment by nick-mcdonald-dtnb** [comment] 2024-02-29 18:03
@Veena11

Looks like it was not listed there as a keychain sharing group! I added that, and it seems to be working on VMs now. 

Very odd that the behavior was only visible on VMs? but it definetly does seem to be working now. 

Thank you for your help 😄

**Comment by Veena11** [comment] 2024-02-29 22:47
Thanks for confirming. You should have seen same behavior on non VM too. Probably MSAL app version you were using on non VM was built with the keychain group added. Closing as the issue is resolved now

**Closed by Veena11** 2024-02-29 22:47 UTC
