### ISSUE TITLE
How to configure XCode to link in MSAL when using integrate_targets = false

### ISSUE THREAD

**Issue by locksleyu** [AzureAD/microsoft-authentication-library-for-objc#1093] opened 2020-09-14 18:21 UTC
I am trying to integrate MSAL into an objective-C project that uses a Podfile with integrate_targets=false (and I cannot change this).

When I build now I get this error:

`ld: library not found for -lMSAL
`

I checked and I see that libMSAL is being built as part of the process, and is ending up here:

`/Users/me/Library/Developer/Xcode/DerivedData/MyApp-ewcfgimmllljvzhlfbgqgmqozhus/Build/Products/Debug-iphoneos/MSAL/libMSAL.a
`

However for some reason the linker is not able to find it, and I don't know how to configure the linker to look at this path.

When I added the library to "Build Phases" / "Link Binaries With Libraries" I dragged and dropped from the libMSAL.a under /Pods/Products, so I would expect Xcode understands the path. (That is the same way I got the above full path.)

Can someone please help out? 

Thanks.

**Comment by locksleyu** [comment] 2020-09-14 19:00
I ended up getting to work by adding "$(BUILT_PRODUCTS_DIR)/MSAL/" to the search path of my main target.

But I'm a little unsure if this is the "right" way. If anybody can confirm this is fine let me know.

**Comment by antrix1989** [comment] 2020-09-15 18:22
By checking the [doc](https://rubydoc.info/gems/cocoapods/Pod%2FInstaller%2FInstallationOptions:integrate_targets), this looks like the right solution to me.

`If set to false, Pods will be downloaded and installed to the `Pods/` directory but they will not be integrated into your project.`

**Comment by oldalton** [comment] 2020-09-28 14:48
Closing as this is by design. Feel free to reopen if needed.

**Closed by oldalton** 2020-09-28 14:48 UTC
Labels: question
