### ISSUE TITLE
Unable To Clear Accounts: "Multiple accounts found in cache."

### ISSUE THREAD

**Issue by AnthonyUccello** [AzureAD/microsoft-authentication-library-for-objc#923] opened 2020-05-05 17:00 UTC
Hello

I have an app where 2 users logged in (on subsequent app launches). Now when I invoke `application.getCurrentAccount` I get the error:

**Couldn't query current account with error: Err domain:MSALErrorDomain code:-50000 userInfo:{ MSALErrorDescriptionKey = "Multiple accounts found in cache."; MSALInternalErrorCodeKey = "-42102"; }**

I figured the issue then was to clear the cache however [there is no api on the cache config](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALCacheConfig.html). My next idea was to get all accounts and sign out the users one by one. However, when I get the accounts object, it crashes when I try to inspect the array or access it in any fashion. 

```
    func signOutAllAccounts()
    {
                guard let applicationContext = self.applicationContext else { return }
        
                let msalParameters = MSALAccountEnumerationParameters()
                msalParameters.completionBlockQueue = DispatchQueue.main
                    
                // TODO implement for multi
                applicationContext.accountsFromDevice(for: msalParameters)
                    { (accounts, error) in
        
                    if let error = error {
                        print("Couldn't query current account with error: \(error)")
                        return
                    }
                    
                    var acts:[MSALAccount] = accounts ?? [] 
                     // acts has 2 objects in it
                    var first = acts.first // crash on access
                }
    }
```

I tried to iterate the accounts but it says it fails to conform

<img width="966" alt="Screen Shot 2020-05-05 at 1 16 13 PM" src="https://user-images.githubusercontent.com/3809669/81095185-aaea9c80-8ed2-11ea-928e-edf16e443502.png">

Even just printing the returned object fails:

<img width="997" alt="Screen Shot 2020-05-05 at 1 27 40 PM" src="https://user-images.githubusercontent.com/3809669/81096363-3dd80680-8ed4-11ea-926f-f480a98c8ceb.png">

Can you advise what else I can do to either log out the accounts or clear the cache? I am unable to getCurrentAccount anymore so login always has to be done manually. (Also note I have cleared my safari cache and that didnt work either)

**Comment by rohitnarula7176** [comment] 2020-05-05 22:38
@AnthonyUccello Can you please specify whether you are trying to build a single account application or a multiple account application. Because the api getCurrentAccount is only intended for single account application. The crash you mentioned shouldn't happen if the accounts array is non-empty. Can you please paste the crash log as well.

**Comment by AnthonyUccello** [comment] 2020-05-06 11:43
I might not have the terminology right but I think the goal was a single but users could change. If single means one and only 1 every login then I would say ours was multiple in this case. 

My solution to logout was to do an interactiveLogin() and do a logout call as soon as the login completed with the account. Using the accounts() would always crash. There is no log for this just the EXE Breakpoint and the Protocol non-compliance messages I showed in the screens.

To reproduce this issue I believe you can do it with the following:
-Login a user interactively (don't log them out and close the app)
-Restart the app, log in as a second user also interactively (close the app)
-Restart the app and try to login silently and you will now get the cache error. 
-Now that you are getting the cache error try to get all accounts --- this will fail

**Comment by jasoncoolmax** [comment] 2020-05-15 22:32
@AnthonyUccello Could you please reproduce the issue and send us the logs? such that we could take a closer look. 
Guidance of collecting the logs is here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=objc#msal-for-ios-and-macos-logging-objc

Regarding  whether we should return nil accounts when there is none in the cache, we created a bug here for tracking: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/929

**Comment by AnthonyUccello** [comment] 2020-05-17 13:10
@jasoncoolmax Sorry I am no longer working on the project that was using this sdk. However the steps I outlined should reproduce the issue.

**Comment by antrix1989** [comment] 2020-05-21 22:11
Closing since we cannot reproduce this.

**Comment by sudeepngeorge** [comment] 2020-09-15 07:19
I also get the exact issue as @AnthonyUccello , witth the same steps mentioned above.

//Pasting the same steps reported by AnthonyUccello
Login a user interactively (don't log them out and close the app)
-Restart the app, log in as a second user also interactively (close the app)
-Restart the app and try to login silently and you will now get the cache error.
-Now that you are getting the cache error try to get all accounts --- this will fail

**Comment by sudeepngeorge** [comment] 2020-09-15 07:21
@AnthonyUccello  Were you able to solve this?

**Comment by locksleyu** [comment] 2020-09-16 22:08
I am seeing the same issue. I can't give repro steps since I don't know exactly what I did, and I don't know how to un-do things so I can try the steps again to repro. 

How can I clear things out? I tried removing the account in MS Authenticator (and device unregister) and deleted that app (and my app) as well.

**Comment by oldalton** [comment] 2020-09-19 01:55
Reopening the issue.

**Comment by NerevarineRule** [comment] 2020-10-12 19:55
Hi @sudeepngeorge  & @locksleyu,

thank you for helping to highlight the issue.

MSALPublicClientApplication actually has a public API that allows you to query multiple accounts, and I believe @AnthonyUccello did not use the correct API to do so. Let me provide you a sample code to do so in Obj-C, assuming that you already have multiple accounts in the cache.

    MSALPublicClientApplicationConfig *config = [[MSALPublicClientApplicationConfig alloc] initWithClientId:clientId
                                                                                                   redirectUri:redirectUri
                                                                                                     authority:authority];
    
    MSALPublicClientApplication *application = [[MSALPublicClientApplication alloc] initWithConfiguration:config error:&error];

Now that you have an instance of MSALPublicClientApplication object, you can do the following:

    if (@available(iOS 13.0, *)) //Currently, this public API requires iOS version 13 or greater.   
    {
        [application accountsFromDeviceForParameters:parameters
                                     completionBlock:^(NSArray<MSALAccount *> * _Nullable accounts, __unused NSError * _Nullable error)
        {
            if (accounts)
            {
                  NSArray<MSALAccount *> *MSALAccounts = accounts;
                  //process accounts 
     
        }];
    }

**Closed** 2020-10-26 21:56 UTC
Labels: question

**Comment by JontyMC** [comment] 2021-11-03 10:00
I also have this issue. I can't see how getAccount is ever viable to use, since as soon as multiple users login, this method will always throw an exception?

**Comment by ramon26cruz** [comment] 2022-10-25 17:57
I also encounter the same issue? What is the fixed for multiple account found issue

**Comment by danielemden** [comment] 2022-12-01 14:20
Removing all accounts from the cache works for me, see https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-java-get-remove-accounts-token-cache

**Comment by asad-mehmood-vendian** [comment] 2024-01-04 11:53
here is help on this we Single Account mode and Multiple account mode. https://azuread.github.io/microsoft-authentication-library-for-objc/

**Comment by qsd-faris** [comment] 2025-09-25 20:01
We are still having this issue, didn't find any solution for Swift to clear accounts/cache. Any help?
