### ISSUE TITLE
Save password auto dismiss in iOS

### ISSUE THREAD

**Issue by sparks2209** [AzureAD/microsoft-authentication-library-for-objc#2084] opened 2024-03-08 16:13 UTC
Hi, can someone help what will be potential fix for this issue, as today by using webViewParameters.webviewType = .safariViewController, the popup for Save Password disappears automatically. And this popup comes only once.

**Comment by kaisong1990** [comment] 2024-03-14 23:04
This is a duplicate of the following. Closing.

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/848

**Closed by kaisong1990** 2024-03-14 23:04 UTC

**Comment by kaisong1990** [comment] 2024-03-14 23:05
@sparks2209 please feel free to post questions and follow up from the above-mentioned thread. Thanks

**Comment by kaisong1990** [comment] 2024-03-14 23:05
@sparks2209 please feel free to post questions and follow up from the above mentioned thread. Thanks
