### ISSUE TITLE
After clicking on cancel Button I am not able to navigate back to the Microsoft login page

### ISSUE THREAD

**Issue by pradweep** [AzureAD/microsoft-authentication-library-for-objc#906] opened 2020-04-16 18:27 UTC
When user was not interested to complete the sign in process, for instance user cancelled the session while user is in password entering screen suppose user clicked on cancel button to end the session. But is there a way to handle the cancel session event so that I can navigate him to the microsoft login page again to the start process from initial screen onwards. Please help me.

**Comment by oldalton** [comment] 2020-04-17 03:04
MSAL would return MSALErrorUserCanceled error when cancellation happens. 
We have an error handling guide here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions?tabs=iosmacos

Does it address your scenario?

**Comment by pradweep** [comment] 2020-04-17 06:34
Hi @oldalton thank you for your quick reply. I can able to partially solve the issue which I am facing, but I am unable to determine whether the user is a valid tenant or not through SDK because not able capture the error in anyway. Can you please guide me how can I determine whether user is a valid tenant or not so that I can provide them through proper alerts to leverage our application. Please help me. Please refer below screenshot for reference of not a valid tenant.
![Screenshot 2020-04-17 at 11 52 16 AM](https://user-images.githubusercontent.com/29473144/79539255-95d4d780-80a3-11ea-8c69-d44088056809.png)

**Comment by oldalton** [comment] 2020-04-17 07:26
I don't think this error is expected. Looks like you're trying to get a token for a tenant where user is not invited. Can you give a little more context about end user scenario? Are you trying to get a token for a specific tenant, or just trying to sign in the user for your app?

**Comment by pradweep** [comment] 2020-04-17 08:09
Question 1: @oldalton according to my context when the user tries to login whose account was not a valid tenant while signing in our app, Is there any call back error from SDK so that I can able to capture the error to navigate him back to custom login page from our app.

Question 2: Is there any way to differentiate between valid tenant user and invalid tenant user errors while user trying to login from the SDK.

**Comment by oldalton** [comment] 2020-04-18 00:07
@pradweep, where do you get the tenant from?
I'd recommend to just go to https://login.microsoftonline.com/common and let AAD discover a valid tenantId for the account.

**Comment by jasoncoolmax** [comment] 2020-04-20 18:21
Hi @pradweep, did you have a chance to try out what Olga mentioned?

I think if you want to detect whether the account is valid to access the tenant, you could also try
1) call acquireToken by going to https://login.microsoftonline.com/common, it will succeed for any user;
2) call acquireTokenSilent by going to https://login.microsoftonline.com/<tenant_id> (what you pass as authority before), if it succeeds silently, it means the user is valid to access the resource.

Let me know if you still face issues.

**Comment by pradweep** [comment] 2020-04-21 09:34
@jasoncoolmax @oldalton  thank you for your quick reply.  

1. We are able to acquire token for all the microsoft users with this url “https://login.microsoftonline.com/common”. It’s working good.

2. We are able to get the token with the tenant_id also i.e., “https://login.microsoftonline.com/<tenant_id>”. This url is working good. If we login with user from Azure Active directory.  
We created a Single_Tenant application from the Azure portal. We are able to authenticate the users form the AAD. 

![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/29473144/79850082-07cd5980-83e1-11ea-9583-e7ae068f41ed.png)

When we try to login with the user is not form the AAD, then we are getting the error like below.

![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/29473144/79850172-27648200-83e1-11ea-93d7-ad6300e96e50.png)

We would like to handle this scenario when the user is not from the AAD. Here, we are not getting any response if the user is not from AAD.

How can we dismiss the web page automatically?. Please help me to resolve this issue asap.

**Comment by rohitnarula7176** [comment] 2020-04-21 18:15
@pradweep We have 2 ways to acquiring token for a resource in our library namely acquireToken and acquireTokenSilent. The first one(acquireToken) is used for interactive auth where you are redirected to a server page. This api will fail to sign in users that are not invited to a particular tenant and the error you are seeing is expected. If you want to handle this error in a silent manner, you can follow the pattern described by Jason in the message above which involves calling acquireTokenSilent for the same user and handling the necessary error.

**Comment by pradweep** [comment] 2020-04-22 09:16
@rohitnarula7176 thank you for your reply. 

**This api will fail to sign in users that are not invited to a particular tenant and the error you are seeing is expected.**

According to the above bold text. If it is as expected, how do we dismiss the “Microsoft Log In” page automatically?

**If you want to handle this error in a silent manner, you can follow the pattern described by Jason in the message above which involves calling acquireTokenSilent for the same user and handling the necessary error.**

According to the above text. Jason described two patterns, we able to authenticate users from AAD with the two cases. Here, we do not have any problem with AAD users.(With two)

To validate with the “acquireTokenSilent” method we need to pass the MSALAccount object. If the user fails, how do we get the token?

we will prepare the document and share the steps with you

**Comment by mipetriu** [comment] 2020-04-23 18:24
@pradweep Both of the steps previously described need to be taken in this situation. Once acquireToken is called to the common endpoint, you should receive a MSALAccount regardless of the AAD invitation status of the user. From there, you can call acquireTokenSilent with the desired tenant to find out if the user is invited to that tenant. Doing this will also keep any errors silent.

**Comment by pradweep** [comment] 2020-04-27 13:53
@mipetriu thank you for your quick reply.
When we call the acquireTokenInteractively method, then the “Microsoft SignIn” will display. If the user fails in the MSALWebView page, how do we know that?
If the user valid then we are getting MSALAccount object.

We are not getting the MSALAccount object if the user is not in the AAD (If the user fails to Login). We used the following code.

func acquireTokenInteractively() {
            
            guard let applicationContext = self.applicationContext else { return }
            guard let webViewParameters = self.webViewParamaters else { return }

            let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
            parameters.promptType = .selectAccount
            
            applicationContext.acquireToken(with: parameters) { (result, error) in
                
                if let error = error {
                    
                    self.updateLogging(text: "Could not acquire token: \(error)")
                    return
                }
                
                guard let result = result else {
                    
                    self.updateLogging(text: "Could not acquire token: No result returned")
                    return
                }
                
                self.accessToken = result.accessToken
                self.updateLogging(text: "Access token is \(self.accessToken)")
                self.updateCurrentAccount(account: result.account)
                self.getContentWithToken()
            }
        }

**Comment by jasoncoolmax** [comment] 2020-04-27 18:01
@pradweep If you just want to know if the user who tries to log in is able to access the tenant, you can do it by following the pattern I mentioned earlier. Pseudo code as below:

```
//Make sure the authority is https://login.microsoftonline.com/common, authority can be set here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/configuration/MSALPublicClientApplicationConfig.h#L53

applicationContext.acquireToken(with: parameters) { (result, error) in

//create a silentParameter, set its authority to be "https://login.microsoftonline.com/<tenant_id>"
//silentParameter.account to be result.account

applicationContext.acquireTokenSilent(with: parameters) { (result, error) in
//check error object to know if the user could be able to sign in your tenant.

}
}
```



If you want to detect all errors that might be happening in the webview, I think that is not possible in OAuth flow.

**Comment by oldalton** [comment] 2020-05-08 21:51
Closing this issue, please reopen if still experiencing any unexpected behavior or if you have additional questions.

**Closed by oldalton** 2020-05-08 21:51 UTC
Labels: question
