### ISSUE TITLE
[Bug] B2C Sign-In with AppleID not redirecting back to application on iOS when using system browser and passcode

### ISSUE THREAD

**Issue by josmithua** [AzureAD/microsoft-authentication-library-for-objc#861] opened 2020-03-05 15:20 UTC
This bug already has an [open issue in the .NET MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1491), but I think it should be opened here, since it's an issue with this objc library.

Please see the linked issue for details. 

It would be really great if this bug was addressed before the Apple Sign-In implementation deadline of April 2020.

Cheers

**Comment by oldalton** [comment] 2020-03-05 18:48
Thank you for opening the issue to bring this to our attention. 

We'll try to get a test setup for Apple ID + B2C from our internal lab team and see if that repros internally.

**Comment by oldalton** [comment] 2020-03-26 07:45
@josmithua Sorry for a delay, took some time to get the test environment setup and running. 

I did some testing for this scenario... and it works well with both WKWebView and ASWebAuthenticationSession options that MSAL library provides for our setup. 

One thing that might be happening is that you're not passing correct redirectUri that MSAL can handle in combination with system browser. WKWebview can handle a wider range of redirectUris, but ASWebAuthenticationSession requires a certain format of the URL that it can handle (for example, https/http Redirect URIs cannot be handled very well). 

Can you please clarify which redirectUri you're passing in your request, and whether you're seeing this issue with ASWebAuthenticationSession?

@jennyf19, since you opened the original issue, can you please also confirm the RedirectUri and specific system browser type that you were using for your testing?

**Comment by josmithua** [comment] 2020-03-26 18:44
Hi @oldalton,

I'm using the redirectUri form as specified in the documentation: `msauth.[BUNDLE_ID]://auth`, and using the default webview (`MSALWebviewTypeDefault`), so I guess `ASWebAuthenticationSession`.

Just tested on an iPhone with iOS 13.3.1, and still seeing the issue.

Whether I even provide a redirectUri or not changes nothing.

**Comment by josmithua** [comment] 2020-03-26 18:56
I just tested with `MSALWebviewTypeWKWebView` and it works, but not with `MSALWebviewTypeAuthenticationSession`

**Comment by oldalton** [comment] 2020-03-27 01:10
@josmithua Would you be able to share your configuration details with me by mailing oldalton@microsoft.com? (I need authority, clientId, BundleId and redirectUri, I can use my own Apple ID for testing). 
There seems to be something different between our configurations.

**Comment by oldalton** [comment] 2020-03-28 00:08
This issue seems to be fixed in iOS 13.4 (and confirmed by the issue reported). Closing the issue. 
The original issue was an Apple bug and was caused by a race condition between Apple ID extension returning result and ASWebAuthenticationSession response handling (webkit was getting cancelled error -999).

**Closed by oldalton** 2020-03-28 00:08 UTC
Labels: needs-information, question
