### ISSUE TITLE
MSAL throwing error(AADSTS70043) for token invalidation even after fetching fresh token interactively.

### ISSUE THREAD

**Issue by rahulcode** [AzureAD/microsoft-authentication-library-for-objc#1212] opened 2021-02-04 05:07 UTC
Issues:   MSAL giving stale token even after fresh interactive login. After fetching fresh tokens, token validation throws an error.

**MSAL 1.1.13**
Authentication is done always in Microsoft Authenticator for fetching new tokens interactively.

Setup :  ADFS + Password Setup.
Conditional Access Policy enforced with 1 hour of Session timings. 

**Bug Type:**
 The bad state of MSAL SDK sitting in Test Application.
  **Not always reproducible, as it happens in some bad state.** 
 Seen this issue 2nd time, hence reporting.  
 
 **Issue Behavior** 

After Continuous testing and performing authentication and cleanup many times, the state of MSAL in Application(Bad state) starts giving Error for token invalidation immediately after fetching a new token from the authenticator.

1. * Fetch New token interactively.
3. * Error Seen: Error is seen for some token that issues and expired a day before (Stale)

` 03/02/2021 13:59:20:754|FLMSALLogManager|logMSALMessage:containsPii:logLevel:[5295]|82<Error>: TID=5366 MSAL 1.1.13 iOS 14.0 [2021-02-03 08:29:20 - 8B18C035-B374-4339-BE88-0FF0C4DED1D5] Processing an AAD error with error code -51412, error invalid_grant, suberror token_expired, description AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-02-02T04:41:55.5620000Z and the maximum allowed lifetime for this request is 3600.
Trace ID: 6e9a9705-fe63-4616-af76-7fde72493700
Correlation ID: 8b18c035-b374-4339-be88-0ff0c4ded1d5
Timestamp: 2021-02-03 08:29:21Z
`

**Summary from logs:**

From Logs, we can see that on 3 Feb, we have fetched the token multiple times, but  immediately after 5 minutes of validation of the token, MSAL starts throwing Error as mentioned above. But looks like MSAL is picking up something from Cache(a day before), the refresh token which was issued on 2021-02-02T04:41:55.5620000Z, and Giving  Error to the Application layer based on the old token. 

The same issue was reported in Authenticator with Logs.  Attached Logs   Authenticator Logs
MSAL callback logs from Application when the issue was seen.  

Note: Issue goes away after doing 2 operations :
 1) Removing Session for the user in the authenticator. 
 2) Doing local cleanup in App by calling (  After calling PpublicClientApp's signoutWithAccount  and remove account method   )   
 
Expected :
After Fetching fresh tokens, MSAL should check for the validity of the new token.

Logs attached:

[Authenticator Logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5923325/Authenticator.Logs.txt)
[MaaS_App_MSAL_Filtered.txt](https://github.com/AzureAD/microsoft-authentication-library-for-objc/files/5923326/MaaS_App_MSAL_Filtered.txt)

![IMG_274DB8B762B7-1](https://user-images.githubusercontent.com/19573187/106847502-09001680-66d5-11eb-80fa-59174f44b83b.jpeg)

**Comment by NerevarineRule** [comment] 2021-02-11 01:14
Hello @rahulcode Could you try to remove the account from MSAL and then try to login again to see if the issue goes away afterwards? If not, could you please provide us repro steps? that will help us tremendously! 


Having seen the log it is indeed returning two RTs, and our logic is always returning the first element in the array in such a case, but this logic was built with the assumption that there would always be one RT in this particular context where this API is used, so this is a very rare case that we have not encountered before, so thank you so much for highlighting it and we will continue to investigate and let you know if we have additional findings. 

Thank you!

**Comment by rahulcode** [comment] 2021-02-26 15:44
After Remove the account the workflows are fine.

As reaching into this state can be a buggy situation for end-users.
What are the next plans to handle such cases?
Are we keeping some sanity check to handle the logic wrt to More than one RT and use the latest one?

Thanks

**Comment by NerevarineRule** [comment] 2021-02-26 17:08
There could be scenarios where the latest RT might not necessarily be the right RT. So I am adding additional logging in the token retrieval logic to better understand where the difference comes from. It would be best to clearly understand the root cause prior to applying the fix. 
Thank you again for bringing up this issue.

**Comment by NerevarineRule** [comment] 2021-03-16 21:48
Next MSAL release will have more robust logging in the code area that resulted in this issue.
Could you help to update your MSAL to the next release, once it becomes available, and then try to reproduce this issue & provide the log again?

Thanks,
Peter

**Comment by NerevarineRule** [comment] 2021-03-16 21:49
I will close this issue until then, since the root cause cannot be identified before the actions I have suggested above is taken.

**Closed** 2021-03-16 21:51 UTC
Labels: question

**Comment by navee4721** [comment] 2022-06-29 21:17
@rahulcode Did you find solution to this , i am facing similar issue. Even after fetching tokens interactively i am seeing bad token
