### ISSUE TITLE
is there a way to hide pop ups 

### ISSUE THREAD

**Issue by xcodeApps** [AzureAD/microsoft-authentication-library-for-objc#844] opened 2020-02-03 08:55 UTC
How can we remove/disable pop ups which comes from library we want to hide these alerts for choosing cert. Our client doesn't want these alerts for users how can we hide those are there any options in the library.

**Comment by oldalton** [comment] 2020-02-03 18:59
Can you please provide an example of the popup that you're talking about (either title of the popup or a screenshot) such as we can provide you with a more specific advice?

**Comment by xcodeApps** [comment] 2020-02-04 09:13
<img width="637" alt="Screenshot 2020-02-03 at 1 54 06 PM" src="https://user-images.githubusercontent.com/32763714/73730291-8dcff180-475c-11ea-81b8-d450eab3382e.png">
<img width="1085" alt="Screenshot 2020-02-03 at 2 24 26 PM" src="https://user-images.githubusercontent.com/32763714/73730327-988a8680-475c-11ea-8433-486ef20e9e20.png">

**Comment by xcodeApps** [comment] 2020-02-04 09:16
we are using broker authentication for some clients as per their need they don’t need these pop ups which asks their internal users for cert and using microsoft.com confirmation

**Comment by oldalton** [comment] 2020-02-04 16:53
Thanks. The first dialog is coming from ASWebAuthenticationSession and is shown by iOS. The only way to hide it is to set prefersEmpheralSession to YES: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(py)prefersEphemeralWebBrowserSession. **However, once you set it to YES, you'll loose SSO with Safari and other apps.** 

For the second dialog, we don't have any control or configuration to change it. In general, system will remember your choice after the first time and not ask again.

**Comment by xcodeApps** [comment] 2020-02-04 17:09
Thanks which means we can not hide/remove those at present.

**Comment by jasoncoolmax** [comment] 2020-02-05 19:11
Closing the issue as it is by design at the current moment.

**Closed by jasoncoolmax** 2020-02-05 19:11 UTC
Labels: question
