### ISSUE TITLE
Unable to see the Sign In web page with MSAL 1.1.12 / 1.1.13 in iOS 14

### ISSUE THREAD

**Issue by wenywang** [AzureAD/microsoft-authentication-library-for-objc#1177] opened 2020-12-16 03:01 UTC
Hi,

I hope you are doing well. 

We are integrating our application with Intune SDK and MSAL, which allows users to login first before using the app:

![Simulator Screen Shot - iPhone 8 Plus - 2020-12-16 at 10 49 35](https://user-images.githubusercontent.com/68687169/102327436-b2256d00-3fc0-11eb-9c98-ebb2576a607a.png)
Recently we have upgraded the Intune SDK to 14.0 and MSAL to 1.1.13. However, we found that on iOS 14 devices the Sign In web page can never be loaded. The web view presents a blank white page:

![Simulator Screen Shot - iPhone 8 Plus - 2020-12-16 at 10 50 47](https://user-images.githubusercontent.com/68687169/102327482-c36e7980-3fc0-11eb-8d03-671c10986913.png)
I tried to downgrade MSAL to 1.1.11 and it works fine. With iOS 13 device and MSAL to 1.1.13 it also works fine. The problem should have been introduced in 1.1.12, with iOS 14.

Could you help to take a look?

Thanks,
Wenyin Wang

**Comment by kaisong1990** [comment] 2020-12-16 23:49
Hi @wenywang Thanks for your question.

We were not able reproduce this issue through our [sample iOS app](https://github.com/Azure-Samples/ms-identity-mobile-apple-swift-objc) running MSAL 1.1.13 on iOS 14.2 devices.

@ShruthiAchutha Since this user mentioned upgraded to Intune SDK 14.0, could you help to take look?

**Comment by wenywang** [comment] 2020-12-18 03:12
Hi @kaisong1990,

Thanks a lot for the response. 
I would like to know whether you are going to release a new version of MSAL by the end of 2020?

Thanks
Wenyin Wang

**Comment by Kyle-Reis** [comment] 2020-12-18 16:38
Hi @wenywang, is the blank authentication prompt shown when you call an Intune enrollment API, or does it happen when initiating a call MSAL directly to acquire a token?

**Comment by kaisong1990** [comment] 2020-12-18 16:55
> Hi @kaisong1990,
> 
> 
> 
> Thanks a lot for the response. 
> 
> I would like to know whether you are going to release a new version of MSAL by the end of 2020?
> 
> 
> 
> Thanks
> 
> Wenyin Wang

Thanks for your question. We don't have a release plan in December, but for January 2021

**Comment by wenywang** [comment] 2020-12-22 06:04
> Hi @wenywang, is the blank authentication prompt shown when you call an Intune enrollment API, or does it happen when initiating a call MSAL directly to acquire a token?

The blank authentication prompt was shown when calling Intune enrolment API. Actually in Info.plist we have set up IntuneMAMSettings with all necessary information such as ADALClientId and ADALRedirectUri, and set AutoEnrollOnLaunch to YES.

**Comment by Kyle-Reis** [comment] 2020-12-22 16:39
Hi @wenywang, I tried configuring a test app with the same settings using same versions of Intune and MSAL, and was not able to reproduce this issue. Which version of Xcode are you compiling the app with?

**Comment by Kyle-Reis** [comment] 2020-12-22 23:06
Hey @wenywang - I was able to reproduce this after resetting the device to clear the keychain.

@kaisong1990 - The root cause of this issue appears to be that MSALPublicClientApplication is returning an error object when accountForUsername is called with a nil username parameter. This was not the case in previous versions of MSAL. Could you look into why that might have changed? There does appear to have been some churn in this area, as the [release notes for 1.1.12](https://github.com/AzureAD/microsoft-authentication-library-for-objc/releases) mention that this method will return nil in this scenario (although I believe MSAL was already doing that? just not also providing an error object in this case). Seems it could be related to that change since @wenywang mentioned this appears to have been introduced with that version.

**Comment by Kyle-Reis** [comment] 2020-12-22 23:15
Go help further in tracking down this issue, here is the error message logged by MSAL when the above is called:

 MSAL 1.1.13 iOS 14.3 [2020-12-22 22:45:13] username is nil or empty which is unexpected, (null), error code: 0

**Comment by kaisong1990** [comment] 2020-12-28 23:34
@Kyle-Reis @wenywang 

Username from accountForUsername is defined as non-nullable in public API. In previous version, it would send back a random account if username is not provided (nil or empty)

There is a new change in 1.1.12/1.1.13 where when developers passed in username as nil/empty, MSAL will throw error back (if developer provided), and return nil back instead of a random account. This is expected.

In order to correct this behavior, please make sure the username is valid before passing into this API

**Comment by kaisong1990** [comment] 2020-12-28 23:46
@Kyle-Reis Also developer mentioned it worked fine with MSAL 1.1.13 on iOS 13, could you help to verify that? The code changes we made in 1.1.12/1.1.13 should not impact specific version

**Comment by Kyle-Reis** [comment] 2020-12-29 20:23
@kaisong1990 - I was not able to reproduce the issue on older iOS versions.

@wenywang - I have a fix for this issue in code review now. It should be available in the next update to the Intune SDK. In the meantime, is it feasible to use version 1.1.11 of MSAL?

**Comment by Kyle-Reis** [comment] 2020-12-29 20:26
Sorry, @kaisong1990 - for clarity, what I meant above was that MSAL does appear to return an error on older iOS versions, as expected.

**Comment by wenywang** [comment] 2020-12-30 02:37
@Kyle-Reis Thanks for the response, could you estimate when will the next version be released?

**Comment by Kyle-Reis** [comment] 2021-01-04 17:21
@wenywang, current estimate is end of this month.

**Comment by Kyle-Reis** [comment] 2021-01-25 22:30
@wenywang - This issue should be addressed with the [latest release](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/releases/latest) of the Intune SDK (version 14.1.0)

**Closed by Kyle-Reis** 2021-01-25 22:30 UTC
Labels: Intune-MAM-question, question
