### ISSUE TITLE
MSAL Causing previews to not work in Xcode 14

### ISSUE THREAD

**Issue by codynedved** [AzureAD/microsoft-authentication-library-for-objc#1590] opened 2022-10-21 15:22 UTC
This issue causes Xcode previews in swiftUI to fail and not load.  This issue was also on the Appcenter library and is in the process of being addressed. 

HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600029299080):'MSAL'>)

**Comment by codynedved** [comment] 2022-11-01 19:16
That is unfortunate.  I think it would be good to support latest dev methodologies and it appears this is the direction of native app development on iOS platform.  Just including this library stops ALLl swiftui previews from working in the project so its impact is huge.

**Comment by swasti29** [comment] 2022-11-18 08:40
@codynedved Previously I meant that we do not support directly swift UI for MSAL instead UI Kit interface. I recommend you to take a look at this tutorial https://medium.com/neudesic-innovation/using-azure-ad-b2c-to-authenticate-ios-app-users-ef3f82435f7d to work MSAL with Swift UI. 
For issues regarding loading Swift UI previews, it is loading perfectly for me after importing MSAL as given in above tutorial. If you are still facing issues with Swift UI previews, Kindly share more regarding the project structure and details regarding importing MSAL.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/12692041/202658148-e751cf9c-07d3-4aa2-b963-e21776757e61.png">

**Comment by DavidKasprzyk** [comment] 2022-12-07 23:12
@swasti29  I have been getting the exact same issue that @codynedved reported for some time (I do think it might be Xcode 14 related). I'm currently using ersion 14.0 (14A309)

When I try to load any preview within my SwiftUI app I get an error message stating "Cannot preview in this file - Unexpected error occurred". Clicking 'Diagnostics' gives:

HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x000060004e37d260):'MSAL'>)

Here's a link to a zip of the generated report that would be sent to Apple: https://www.icloud.com/iclouddrive/001GeEtm23PpbVOFdJ8JCzkyQ#previews-diagnostics-20221207-150943

Note that if I remove the MSAL library from the 'Link Binary With Libraries' build phase, all my previews work fine.

**Comment by swasti29** [comment] 2022-12-15 03:41
@DavidKasprzyk I could not able to reproduce the issue with loading Swift UI previews on Xcode 14. If using SPM for importing MSAL, I would suggest to remove "type: .static" in package.swift as given here: https://developer.apple.com/forums/thread/707569.
Kindly go through the thread: https://developer.apple.com/forums/thread/707569.

**Comment by DavidKasprzyk** [comment] 2022-12-15 04:39
@swasti29 this was definitely using SPM and I'm pulling it into my Xcode project not another package, so their is no 'type' to define. While I could fork my own version of MSAL to make an updated package, that's a workaround, not an actual fix.

However, I did test and Xcode 14.1 seems to have changed how it's handling MSAL's package and previews do now seem to be loading even with the library linked.

**Comment by swasti29** [comment] 2022-12-21 20:43
@DavidKasprzyk Since the issue is resolved with Xcode 14.1, closing the thread.

**Closed by swasti29** 2022-12-21 20:43 UTC
Labels: question
