### ISSUE TITLE
How can I handle browser clicks? Suppose, if I will have to handle a certain link how can I take control of webview in iOS?

### ISSUE THREAD

**Issue by kirthika** [AzureAD/microsoft-authentication-library-for-objc#223] opened 2017-09-06 07:13 UTC
Suppose, if I will have to handle a certain link how can I take control of webview in iOS?

**Comment by RPangrle** [comment] 2017-10-09 21:29
This is out of scope for a GitHub issue. MSAL uses a System Web View which by design you do not have control over from the context of the application. The application taking control over it is a security violation. If you're looking to automate it you should investigate a UIAutomation based solution like Appium.

**Closed by RPangrle** 2017-10-09 21:29 UTC
