### ISSUE TITLE
Switching back from Auth app no longer provides bundleID of the Auth app

### ISSUE THREAD

**Issue by Sudlon** [AzureAD/microsoft-authentication-library-for-objc#884] opened 2020-03-27 09:49 UTC
Hi, I ran into the following situation:

I use the MSAL SDK to get an access token using the Authenticator app as the broker (no problem there), but at the point where my app takes over the flow I no longer receive any "options" in the "life cycle" method in the AppDelegate class. I'm talking about the following method:
`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool`

The options now contain the following value:
`[__C.UIApplicationOpenURLOptionsKey(_rawValue: UIApplicationOpenURLOptionsOpenInPlaceKey): 0]`

The last time I was working on this (about a month ago) I still received options among which source application: i.e. bundle ID of the Authenticator app. I used this to check whether the source app is indeed the Authenticator app. Now I needed to remove this check. Not sure if that really is a bad thing, but I am still wondering what changed and why. Did anything change in the MSAL SDK?

PS: I'm relatively new to developing in iOS so maybe I'm asking in the wrong place but since I ran into this when integrating the MSAL SDK I thought I'd start here.

**Comment by rohitnarula7176** [comment] 2020-03-27 18:01
@Sudlon Can you tell us whether you were previously testing this on iOS 12 and now you are on iOS 13?

**Comment by Sudlon** [comment] 2020-03-31 08:54
@rohitnarula7176 to be honest I'm not 100% sure what I tested this on before, but right now it is indeed on iOS 13. Since you mentioned this I just checked on a iOS 12 device and then I do get the bundle ID (among other info). So I guess I probably tested this on an iOS 12 device. Thanks for the insight.

Follow up question: is there another way of checking whether the "source application" is the correct one, or is this not really necessary?

**Comment by jasoncoolmax** [comment] 2020-04-01 17:50
@Sudlon Since iOS 13, Apple won't provide source application to an app unless the caller app and receiver app are signed by the same cert. That being said, your app won't get source application because your app and Authenticator app are signed by different certs.

To mitigate this issue, we send nonce to broker and get back nonce from broker. If those nonce are not consistent, we will throw an error. So for now, I don't think there is a way for your app to check the source application.

**Comment by jasoncoolmax** [comment] 2020-04-06 18:06
Close it because it is by design. Feel free to reopen it if you still see issues. Thanks!

**Closed by jasoncoolmax** 2020-04-06 18:06 UTC
Labels: question
