### ISSUE TITLE
v0.2 Missing from Cocoapod podspec repo

### ISSUE THREAD

**Issue by barnstar** [AzureAD/microsoft-authentication-library-for-objc#353] opened 2018-09-20 20:09 UTC
I had been using the 0.2.2 preview which seems to have disappeared from the CocoaPods podspec repo (0.2.2 because of errors in 0.2.3).   The newest available version in the podspec now is 0.1.4 which lacks the features I require.

Can we get this latest version (0.2?) back into CocoaPods?

$pod update
$pod spec cat MSAL
{
  "name": "MSAL",
  "version": "0.1.4",
  "summary": "Microsoft Authentication Library (MSAL) Preview for iOS",
.....

**Comment by deregtd** [comment] 2018-09-20 22:53
FWIW, 0.1.4 doesn't compile for me in XCode without modification. It references "IdentityCore_Internal.h", which doesn't exist anywhere.

**Comment by oldalton** [comment] 2018-09-21 01:32
Thanks for reporting those issues.
1. The 0.2.2 version wasn't maintained by Microsoft. It was created by another dev it was basically a wrapper around official MSAL (and we weren't aware of that until we tried to push our own official Pod). The versioning of that Pod was different from MSAL versioning and we can't control that. We now took over the official MSAL cocoa pods and pointing it to correct repository with correct versions. We're sorry for the inconvenience, but we wanted to move everyone to official Microsoft maintained pod. 

Regarding features you need, @barnstar what are those features? The other pod was just a wrapper around MSAL and was exposing refresh tokens to developer. It must have had the same feature set as MSAL.

2. @deregtd How're you consuming MSAL? MSAL uses submodules that your checkout can't find.
Carthage will find the submodules by default. If you're using CocoaPods and pointing to a different branch, you need to add this to your pod file: :submodules => true
If you're using the official latest MSAL in Cocoapods, it should work without modifications of your pod file.
If you're using MSAL as a submodule, make sure you run the "git submodule update --recursive" command. 
If you're downloading the latest MSAL release from Github, make sure you download the release package and not the source code.
If you're just downloading zip of the branch, then Github currently doesn't support fetching submodules automatically. You should clone the branch and run the "git submodule update --recursive" command instead. 
Please let me know if those instructions help.

**Comment by oldalton** [comment] 2018-09-21 01:33
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/332

**Comment by deregtd** [comment] 2018-09-21 04:45
Aha interesting!  The submodules thing fixed, it thanks!  The install instructions I copied didn't have any mention of that, which worked fine until 0.1.4.  May want to put that on your front page for cocoapod installers. :)

**Comment by oldalton** [comment] 2018-10-08 17:06
Looks like the issues were resolved. Please reopen this issue if you experience any more problems. Closing for now.

**Closed by oldalton** 2018-10-08 17:06 UTC

**Comment by JoNilsson** [comment] 2020-02-07 02:37
Thank you @oldalton!  
Just found this helpful while trying out the ADAL 4.0.6 branch.  
Adding `:submodules => true` resolved the missing import in the precompile header that ref'd `IdentityCore_Internal.h`

**Comment by oguzhangedik** [comment] 2020-05-19 01:36
Thank you @oldalton

pod 'ADAL', :git => 'https://github.com/AzureAD/azure-activedirectory-library-for-objc.git', :tag => '4.0.7', :submodules => true

That works without error anymore.
