### ISSUE TITLE
iOS user unable to authenticate, prompting them to enable Cookies when they already are

### ISSUE THREAD

**Issue by guidedways** [AzureAD/microsoft-authentication-library-for-objc#1107] opened 2020-09-25 14:55 UTC
We've got a strange case where a user's saying they see the following notice when trying to authenticate. In his exact words: I can’t connect to it because the authentication window tells me I need to allow cookies. However, in both Safari and Brave, my two browsers, I have allowed cookies, but still Microsoft says cookies are blocked.

The logs show normal 5005 errors and there's nothing for us to diagnose further. I don't know what to advise. We're using the latest version of MSAL.

![IMG_BC432CBEC106-1](https://user-images.githubusercontent.com/202437/94282296-b19cad80-ff60-11ea-9b6d-e957686cba46.jpeg)

**Comment by oldalton** [comment] 2020-09-25 15:07
Can you try following on your device `Settings > Safari > Block Cookies and set it to Never`
Looks similar to this: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/928
Seems external to MSAL.

**Comment by guidedways** [comment] 2020-09-25 15:08
@oldalton interesting, I'll ask them to give it a try and get back to you shortly.

**Comment by guidedways** [comment] 2020-09-27 12:28
Unfortunately that didn't help. They've tried various things and it still fails to work. Worth mentioning that it's only MSAL auth failing, AppAuth / Google is working fine.

**Comment by oldalton** [comment] 2020-09-28 14:41
Thanks, do you mean that auth for the same AAD tenant works with AppAuth, but not with MSAL?
Or that Google auth works with AppAuth, but AAD auth doesn't work with MSAL?

Perhaps user has somehow opted out from cookie usage?

**Comment by guidedways** [comment] 2020-09-29 12:24
No sorry what I meant was that they're only seeing this for MSAL related authentication. We use OUTH2 (and a similar library called AppAuth to authenticate google accounts) and that seems to work okay for them. They're only seeing this issue when they try and authenticate their O365 account.

**Comment by guidedways** [comment] 2020-09-29 13:38
The user's finally had success. Apparently they had installed "1Blocker" for iOS - some kind of Safari plugin for blocking trackers. It seems to have blocked cookies for MSAL too somehow inadvertently. That's a shame though - is there no way for Microsoft's authentication to work if a plugin's blocking cookies?

**Comment by oldalton** [comment] 2020-09-29 14:26
Thank you for reporting back. This is very useful information and explains why this behavior was seen regardless of cookie cleaning operation. Let me research this topic.

**Comment by oldalton** [comment] 2020-09-29 22:34
I followed up and this is by design. It seems that 1Blocker is not just blocking all cookies, but blocking Google and AAD cookies differently. I'd recommend reporting this to the 1Blocker app support team.

Closing as by design.

**Closed by oldalton** 2020-09-29 22:34 UTC
Labels: question
