### ISSUE TITLE
Authentication Issues ( Cert based / ADFS Password ) (1.1.10- Prompttype .selectAccount  V/S. .login )

### ISSUE THREAD

**Issue by rahulcode** [AzureAD/microsoft-authentication-library-for-objc#1106] opened 2020-09-25 07:51 UTC
MSAL 1.1.10

Issue :

Certificate based authentication  not working with parameters.promptType = .login ( Sign In Certificate is not shown in Login Page ), Works with promptType = .selectAccount

Certificate and server trust certificates are installed manually into the device.

Tried the same with Sample MSAL App.

` func acquireTokenInteractively() {
        
        guard let applicationContext = self.applicationContext else { return }
        guard let webViewParameters = self.webViewParamaters else { return }

        let parameters = MSALInteractiveTokenParameters(scopes: kScopes, webviewParameters: webViewParameters)
        **parameters.promptType = .selectAccount**
        
        
        parameters.loginHint = "XXXX@f30.redroverlife.com"
        
        let claimRequest = MSALClaimsRequest();
        let individualClaimRequest =  MSALIndividualClaimRequest(name: "deviceid")
        individualClaimRequest.additionalInfo = MSALIndividualClaimRequestAdditionalInfo()
        individualClaimRequest.additionalInfo?.essential = NSNumber(integerLiteral: 1)
        parameters.claimsRequest = claimRequest
        
        do {
            try claimRequest.requestClaim(individualClaimRequest, for: .accessToken)
        } catch let error as NSError {
            print(error.description)
        }
        
        applicationContext.acquireToken(with: parameters) { (result, error) in
            
            if let error = error {
                
                self.updateLogging(text: "Could not acquire token: \(error)")
                return
            }
            
            guard let result = result else {
                
                self.updateLogging(text: "Could not acquire token: No result returned")
                return
            }
            
            self.accessToken = result.accessToken
            self.updateLogging(text: "Access token is \(self.accessToken)")
            self.updateCurrentAccount(account: result.account)
            self.getContentWithToken()
        }
    }`

**Tried the following: **

        `parameters.promptType = .login` (  Not working )
In another case, it not show the _Sign in with Certificate_

        `parameters.promptType = .selectAccount` ( Working )
Working means login page will show _Sign in with Certificate_

**Video Link:** https://ibm.box.com/s/lv7zzxei0mqfm4e30iywg0hppa0wu63f

**Comment by rahulcode** [comment] 2020-09-25 07:53
**Working :**
![Sign in using a certificate](https://user-images.githubusercontent.com/19573187/94241373-33c1ad80-ff32-11ea-9c92-c5b9264c38b3.jpg)

**Not Working :**
![Not certificagte](https://user-images.githubusercontent.com/19573187/94241384-36bc9e00-ff32-11ea-93c5-a4c226cf3d53.jpg)

**Comment by rahulcode** [comment] 2020-09-25 10:21
Hi Folks

Similarly for ADFS + Password Setups

Description :
If .login type is used for interactive authentication request, then the Authenticator app ended up showing below error.
(Works with .selectAccount type option )

.login
--------------------------------------------------

Launch URL :

msauthv2://broker?msg_protocol_ver=3&authority=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon&broker_nonce=24E4D1F9-1220-412D-9A3A-974804F5EFDC&prompt=login&scope=urn%3Ams-drs%3Aenterpriseregistration.windows.net%2F.default&login_hint=azure1%40f21.redroverlife.com&application_token=Q3ylV9Cn-leTbO4jv19ZR_k9yRWTNTkCnkEmbprEIiA0C6XWRV5n8-3MTrm-vDP3fR89Atl-W_0iY5CIbufNGbcCyHQWEHhTWMTtcxVX6ahCz7Zse0UvzjNhJcBpNtcOOF2FoK9lGeVCaG1UwimK0wy8G4LtIPT6t3wb8UehFwM&client_version=1.1.10&client_app_name=MSALiOS_1&broker_key=27O2hQBTqQvbGF2UHztJ4Xtos3tsHHl4uVUZthaC1B4&claims=%257B%2522access_token%2522%253A%257B%2522deviceid%2522%253A%257B%2522essential%2522%253Atrue%257D%257D%257D&redirect_uri=msauth.com.fiberlink.maas360.enterpriseappstore%3A%2F%2Fauth&correlation_id=3F9FD812-3705-480A-ACDE-6E836CFE8ED4&client_id=f8a93a2d-0d83-4828-8906-d911ef0ba699&extra_oidc_scopes=openid+profile+offline_access&client_app_version=1.0
![Uploading Qery_parameter.png…]()

Error :

expression produced error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x0).
The process has been returned to the state before expression evaluation.

![image](https://user-images.githubusercontent.com/19573187/94255988-ba808580-ff46-11ea-9512-b4c44e063dc8.png)

--------------------------------------------------
ADFS Password  ( Sample Application )
.selectAccount

Working :
msauthv2://broker?msg_protocol_ver=3&authority=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon&broker_nonce=26F62BDA-0B47-4168-8ADC-1E0468E6E17A&prompt=select_account&scope=urn%3Ams-drs%3Aenterpriseregistration.windows.net%2F.default&login_hint=azure1%40f21.redroverlife.com&client_version=1.1.10&client_app_name=MSALiOS_1&broker_key=27O2hQBTqQvbGF2UHztJ4Xtos3tsHHl4uVUZthaC1B4&claims=%257B%2522access_token%2522%253A%257B%2522deviceid%2522%253A%257B%2522essential%2522%253Atrue%257D%257D%257D&redirect_uri=msauth.com.fiberlink.maas360.enterpriseappstore%3A%2F%2Fauth&correlation_id=6FCD7344-B655-4CBE-AA5C-731570152133&client_id=f8a93a2d-0d83-4828-8906-d911ef0ba699&extra_oidc_scopes=openid+profile+offline_access&client_app_version=1.0


--------------------------------------------------

**Comment by rahulcode** [comment] 2020-09-25 10:30
Note :  

For Azure Only users it works properly with .login prompt type.
The issue is only with ADFS Accounts.

**Comment by oldalton** [comment] 2020-09-25 14:55
Thanks for reporting this issue. We don't really control how ADFS behaves and reacts to different prompt types. This is something that should be checked for a particular ADFS configuration by its admin.

**Comment by smudireddy** [comment] 2020-09-25 17:13
What configuration we need to check on Admin side of ADFS ?. Is there any particular param in request or response will end up in this that instead of cert option only password option shown to user ?. If that is the case then what is the difference in request with PromptType as .login to .SelectAccount ?

**Comment by oldalton** [comment] 2020-09-25 22:18
I think it's documented here: https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-user-certificate-authentication#check-if-azure-ad-promptloginbehavior-is-configured-correctly-on-your-federated-domain-settings

```
Many Office 365 applications send prompt=login to Azure AD. Azure AD, by default, converts it to a fresh password login to AD FS. As a result, even if you have configured certificate authentication in AD FS, your end users will only see a password login.
Get the federated domain settings using the ‘Get-MsolDomainFederationSettings' command let
Ensure that PromptLoginBehavior parameter is set to one of ‘Disabled' or ‘NativeSupport'
```

**Comment by smudireddy** [comment] 2020-09-26 01:04
Thanks @oldalton  for the info, We seen the point here in the above link explained the case.

_Many Office 365 applications send prompt=login to Azure AD. Azure AD, by default, converts it to a fresh password login to AD FS. As a result, even if you have configured certificate authentication in AD FS, your end users will only see a password login.__

QQ >>> Does the configuration change you suggested has any impact on a case where Admin want to provide both login options to end user on the ADFS auth web page and MSAL integrated app made a request to Authenticator App with prompt type as **.login**. ?

**Comment by oldalton** [comment] 2020-09-28 14:45
@smudireddy, it largely depends on the ADFS version of the customer. I'd recommend checking with [this documentation](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/ad-fs-prompt-login). 

In general, I'd also advise against using prompt=login as it has many other unintended consequences. For example, prompt=login is not compatible with the combination of certificate based authentication and AAD device registration.

**Comment by oldalton** [comment] 2020-09-29 22:41
Closing as by design.

**Closed by oldalton** 2020-09-29 22:41 UTC
Labels: question
